#!/bin/zsh

load_os_based_conf () {
    tmux_home=~/.tmux

    if [ $OPERATING_SYSTEM = "macos" ] ; then
        tmux source-file "$tmux_home/tmux_macos.conf"
        exit
    else
        tmux source-file "$tmux_home/tmux_linux.conf"
        exit
    fi
}

load_os_based_conf
